FROM php:8.2-apache

# Habilita mod_rewrite (opcional)
RUN a2enmod rewrite

# Instala extensões necessárias
RUN docker-php-ext-install pdo pdo_mysql

# Copia arquivos da API
COPY . /var/www/html/

# Permissões
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80